### ISSUE TITLE
Mubashir

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/MIS#17]

**Comment by mubashir633** [comment]
casecade drop down of department and designation (DONE)
user name according to login(DONE)
user ,deprtmnt and designation should not be duplicate

**Comment by mubashir633** [comment]
Edit Profile **Fixed**
Change Password **Fixed**
Double Click for Edit **Fixed**
Plus Sign Button for Add **Fixed**

**Comment by mubashir633** [comment]
1. Assessment 
2. Expense type 
3. Manage Expense
4. Good transfer
5. Regret Letter
6. Delivery note and items 
7. Receiving note and items

Validation, button position, BlockUI, Add , Edit

**Comment by mubashir633** [comment]
Did delivery note today its almost complete just having one issue will resolve it tonight.
