### ISSUE TITLE
Editing in Left Menu

### ISSUE THREAD

**Issue by syedziahaq** [serviceproviderpk/MIS#29]
There is one query, if we click on multiple tabs, all tab are still open. Logicaly, wen we  click the next tab, previous tab will be closed automatically e.g. we open HR tab, after that we click "Program" tab in that situation HR tab must  be  closed but both will be remain open.
kindly assign different color codes for every tab i.e. Operations may be dark Blue color,       Program may be light green color, System setting may be light brown color, and Active tab must be in Other Color with Bold Font

**Comment by serviceproviderpk** [comment]
@syedziahaq  Can you  please choose color code  (http://htmlcolorcodes.com/) and send us color code.

Thanks,

**Comment by syedziahaq** [comment]
Operations: 
HEX #2e86c1 	RGB 46, 134, 193 		HSL 204, 62%, 47% 

Program
HEX#58d68d 	RGB88, 214, 141 		HSL145, 61%, 59% 

User Setting
HEX#ebdef0 		RGB 235, 222, 240 		HSL 283, 39%, 91% 

Active Tab Color
HEX #f4d03f 	RGB244, 208, 63 		HSL48, 89%, 60%

**Comment by syedziahaq** [comment]
Dear Asif Bhai and Zahid Bhai,

If I assign  rights to "concern head" or "proc manager", left menu  remain still blank. I already shared this matter Zahid

**Comment by serviceproviderpk** [comment]
Fixed, Please test and give your feedback.

**Comment by serviceproviderpk** [comment]
I assumed @ZahidRavian Zahid has already updated you, but we forgot to update status here.
