### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by syedziahaq** [serviceproviderpk/MIS#41]
Please add "PMS" logo on the login page
Make the page more smart, decrease the size of  the log in box
![image](https://cloud.githubusercontent.com/assets/25702187/26806641/724967d4-4a6b-11e7-8772-f092b65fd7a8.png)

**Comment by syedziahaq** [comment]
I have email the logo

**Comment by serviceproviderpk** [comment]
@WaqarShah  Please check forget  email. remove some dummy text, from email. and show proper information.
